version: "3.7"

networks:
  n3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.210.0.0/24
  n4:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.220.0.0/24
  n6:
    external: true
  n7:
    driver: bridge
  n8:
    driver: bridge
  n10:
    driver: bridge
  n11:
    driver: bridge
  n12:
    driver: bridge
  n13:
    driver: bridge
  n15:
    driver: bridge
  sbi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/24

services:
  mongodb:
    networks:
      sbi:
        ipv4_address: 172.200.0.160 
    image: mongo:4.2
    container_name: free5gc-mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
  amf:
    networks:
      - sbi
      - n11
      - n12
      - n15
    image: free5gc-v2
    container_name: free5gc-amf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/amfcfg.conf:/root/free5gc/config/amfcfg.conf
      - ./support/TLS/amf.pem:/root/free5gc/support/TLS/amf.pem
      - ./support/TLS/amf.key:/root/free5gc/support/TLS/amf.key
    entrypoint:
      - ./amf

  smf:
    networks:
      sbi:
        ipv4_address: 172.200.0.190 
      n7:
      n11:
      n10:
      n4:
        ipv4_address: 172.220.0.190 
    image: free5gc-v2
    container_name: free5gc-smf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/smfcfg.conf:/root/free5gc/config/smfcfg.conf
      - ./support/TLS/smf.pem:/root/free5gc/support/TLS/smf.pem
      - ./support/TLS/smf.key:/root/free5gc/support/TLS/smf.key
    entrypoint:
      - ./smf

  pcf:
    networks:
      - sbi
      - n7
      - n15
    image: free5gc-v2
    container_name: free5gc-pcf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/pcfcfg.conf:/root/free5gc/config/pcfcfg.conf
      - ./support/TLS/pcf.pem:/root/free5gc/support/TLS/pcf.pem
      - ./support/TLS/pcf.key:/root/free5gc/support/TLS/pcf.key
    entrypoint:
      - ./pcf

  ausf:
    networks:
      - sbi
      - n8
      - n12
      - n13
    image: free5gc-v2
    container_name: free5gc-ausf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/ausfcfg.conf:/root/free5gc/config/ausfcfg.conf
      - ./support/TLS/ausf.pem:/root/free5gc/support/TLS/ausf.pem
      - ./support/TLS/ausf.key:/root/free5gc/support/TLS/ausf.key
    entrypoint:
      - ./ausf

  nrf:
    networks:
      sbi:
        ipv4_address: 172.200.0.180 
    image: free5gc-v2
    container_name: free5gc-nrf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/nrfcfg.conf:/root/free5gc/config/nrfcfg.conf
      - ./support/TLS/nrf.pem:/root/free5gc/support/TLS/nrf.pem
      - ./support/TLS/nrf.key:/root/free5gc/support/TLS/nrf.key
    entrypoint:
      - ./nrf

  nssf:
    networks:
      - sbi
    image: free5gc-v2
    container_name: free5gc-nssf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/nssfcfg.conf:/root/free5gc/config/nssfcfg.conf
      - ./support/TLS/nssf.pem:/root/free5gc/support/TLS/nssf.pem
      - ./support/TLS/nssf.key:/root/free5gc/support/TLS/nssf.key
    entrypoint:
      - ./nssf

  udm:
    networks:
      - sbi
      - n13
      - n10
      - n8
    image: free5gc-v2
    container_name: free5gc-udm
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/udmcfg.conf:/root/free5gc/config/udmcfg.conf
      - ./support/TLS/udm.pem:/root/free5gc/support/TLS/udm.pem
      - ./support/TLS/udm.key:/root/free5gc/support/TLS/udm.key
    entrypoint:
      - ./udm

  udr:
    networks:
      - sbi
    image: free5gc-v2
    container_name: free5gc-udr
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/udrcfg.conf:/root/free5gc/config/udrcfg.conf
      - ./support/TLS/udr.pem:/root/free5gc/support/TLS/udr.pem
      - ./support/TLS/udr.key:/root/free5gc/support/TLS/udr.key
    entrypoint:
      - ./udr

  upf:
    privileged: true
    networks:
      n6:
      n3:
        ipv4_address: 172.210.0.170 
      n4:
        ipv4_address: 172.220.0.170 
    image: free5gc-v2
    container_name: free5gc-upf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./config/upfcfg.yaml:/root/free5gc/config/upfcfg.yaml
    entrypoint:
      - ./free5gc-upfd
